/*
  @file plugins/plugins.hpp

  Includes all plugins. Auto-generated by KRONOS Plugin Manager
*/

#ifndef _PLUGINS_HPP_
#define _PLUGINS_HPP_

namespace KPlugins {
  namespace Resources {
  }
}

#endif
