/*
  @file plugins/plugins.hpp

  Includes all plugins. Auto-generated by KRONOS Plugin Manager
*/

#ifndef _PLUGINS_HPP_
#define _PLUGINS_HPP_

#include <fstream>
#include <iterator>
#include <map>
#include <vector>

namespace KPlugins {
  #include "plugins/autonreader.hpp"

  namespace Resources {
    #include "plugins/resources/autons.hpp"
  }
}

#endif
