name: cppcheck

on: [push]

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cppcheck
        run: |
          brew update \
          brew install cppcheck

      - name: Run cppcheck
        run: ./scripts/cppcheck.sh
