name: Make

on: 
  push:
    branches-ignore:
      - 'stable'
    paths-ignore:
      - '.github/**'
      - '**.md'
      - '**.gitignore'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SUBMODULE_KEYS }}
          submodules: recursive

      - name: Install arm-none-eabi-gcc
        uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: '9-2019-q4'
        
      - name: Make code
        run: make