name: ProsMake

on: [push]

jobs:
  prosMake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install python3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install pros-cli
        run: pip install pros-cli

      - name: Install arm-none-eabi-gcc
        run: curl -Ls "https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2" -o gcc-arm-none-eabi.tar.bz2 && tar -xjf gcc-arm-none-eabi.tar.bz2 && echo "$PWD/gcc-arm-none-eabi-10.3-2021.10/bin" >> $GITHUB_PATH

      - name: Compile
        run: pros make
